### PR TITLE
Release v1.1.0

### PR DESCRIPTION
**Pull request by JohnTitor**
It's time to release v1.1.0 🦇 
cc: #70 

CHECK LIST:

* updates CHANGELOG
* increments version number

r? @k-nasa

### CODE REVIEW

**Comment by KoujiroFrau** [comment]
:pushpin: Commit b0847b7afefa05c75ae8f6d767f150d3fc76f16b has been approved by `k-nasa`

**Comment by JohnTitor** [comment]
@KoujiroFrau r=k-nasa

**Comment by KoujiroFrau** [comment]
:pushpin: Commit b0847b7afefa05c75ae8f6d767f150d3fc76f16b has been approved by `k-nasa`

**Comment by KoujiroFrau** [comment]
:hourglass: b0847b7afefa05c75ae8f6d767f150d3fc76f16b has been merged into the auto branch adc102a3c2c5c846df8e79f9a45853368d089e9e

**Comment by KoujiroFrau** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [Your tests passed on CircleCI!](https://circleci.com/gh/student-kyushu/frau/54?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

**Pull request merged**
