### PR TITLE
docs: Add Go Report badge

### PR DESCRIPTION
**Pull request by JohnTitor**
To make README rich! And we can check the quality of frau.

r? @ghost

### CODE REVIEW

**Comment by JohnTitor** [comment]
@JohnTitor Hey, can you review this?

**Comment by JohnTitor** [comment]
@JohnTitor Oh, awesome!

@KoujiroFrau r+

**Comment by JohnTitor** [comment]
Hmm, if the comment includes multiple mention, it seems that frau cannot parse.

@KoujiroFrau r+

**Comment by KoujiroFrau** [comment]
:pushpin: Commit 91928e53935706911639431d8fc4a437ade89103 has been approved by `JohnTitor`

**Comment by KoujiroFrau** [comment]
:hourglass: 91928e53935706911639431d8fc4a437ade89103 has been merged into the auto branch b08d4a307d30c13fa3f6cf24ee8a5e4a6e66d1a2

**Comment by KoujiroFrau** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [Your tests passed on CircleCI!](https://circleci.com/gh/student-kyushu/frau/40?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

**Pull request merged**
