### PR TITLE
minor: Fix import path

### LINKED ISSUE #29: Fix import path
I transferred this repo, we know what to do next, don't we?

### PR DESCRIPTION
**Pull request by JohnTitor**
Fixes #29 

r? @JohnTitor @KoujiroFrau

### CODE REVIEW

**Comment by JohnTitor** [comment]
@KoujiroFrau r+

**Comment by KoujiroFrau** [comment]
:pushpin: Commit 5f741ce3998f97424e0511e2410208666ee59419 has been approved by `JohnTitor`

**Comment by KoujiroFrau** [comment]
:hourglass: 5f741ce3998f97424e0511e2410208666ee59419 has been merged into the auto branch 86fc5f3ef572093d1de343a8bdf47833afcafbef

**Comment by KoujiroFrau** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/student-kyushu/frau/builds/485630134?utm_source=github_status&utm_medium=notification)

**Pull request merged**
