### PR TITLE
chore: Adjust import style

### PR DESCRIPTION
**Pull request by JohnTitor**
ref. https://github.com/google/go-github#usage

### CODE REVIEW

**Comment by yaminoma** [comment]
LGTM

**Comment by yaminoma** [comment]
@KoujiroFrau r+

**Comment by KoujiroFrau** [comment]
:pushpin: Commit c0307032816caae6ec1807c2ca1427dafb2f5086 has been approved by `yaminoma`

**Comment by KoujiroFrau** [comment]
:hourglass: c0307032816caae6ec1807c2ca1427dafb2f5086 has been merged into the auto branch bc2f91633e24676731dff0c31409fe7b811df0b0

**Comment by KoujiroFrau** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [Your tests passed on CircleCI!](https://circleci.com/gh/student-kyushu/frau/44?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

**Pull request merged**
