### PR TITLE
fix: Improve output

### PR DESCRIPTION
**Pull request by JohnTitor**
This pull-req fixes:

* Replaces Printf with Println
* Adds `\n` and `:` to some messages

### CODE REVIEW

**Comment by JohnTitor** [comment]
This is minor changes, not affect almost features, I think.

@KoujiroFrau r+

**Comment by KoujiroFrau** [comment]
:pushpin: Commit bf616def13b65dd0d93a5f42ac6172f4eefe60f9 has been approved by `JohnTitor`

**Comment by KoujiroFrau** [comment]
:hourglass: bf616def13b65dd0d93a5f42ac6172f4eefe60f9 has been merged into the auto branch f26ca8706a1434737ad13f8c318094d8682191aa

**Comment by KoujiroFrau** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [Your tests passed on CircleCI!](https://circleci.com/gh/student-kyushu/frau/36?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

**Pull request merged**
