### PR TITLE
Bye Travis CI 😢

### PR DESCRIPTION
**Pull request by JohnTitor**
It's tedious to run two CI services. We should use CircleCI only.

### CODE REVIEW

**Comment by JohnTitor** [comment]
Or we can use Travis CI to check status before being reviewed, you may do at your pleasure.

**Comment by JohnTitor** [comment]
Okay, I want to merge this. If needing Travis CI, we'll re-add config file.

@KoujiroFrau r+

**Comment by KoujiroFrau** [comment]
:pushpin: Commit e0e6d27a9e8beb3ab0d15da0bbc6937950ed7296 has been approved by `JohnTitor`

**Comment by KoujiroFrau** [comment]
:hourglass: e0e6d27a9e8beb3ab0d15da0bbc6937950ed7296 has been merged into the auto branch 944e87c5e84703aa4906ab5e179674a671a477ed

**Comment by KoujiroFrau** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [Your tests passed on CircleCI!](https://circleci.com/gh/student-kyushu/frau/32?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

**Pull request merged**
