### PR TITLE
style: Fixes some issues following Go Report

### PR DESCRIPTION
**Pull request by JohnTitor**
This changes as follows:

* Fixes typo
* Makes code simple

r? @ghost

### CODE REVIEW

**Comment by yaminoma** [comment]
LGTM 👍

**Comment by yaminoma** [comment]
@KoujiroFrau r+

**Comment by KoujiroFrau** [comment]
:pushpin: Commit c20ac52230bea22944e73a311bfbde192b32b01a has been approved by `yaminoma`

**Comment by KoujiroFrau** [comment]
:hourglass: c20ac52230bea22944e73a311bfbde192b32b01a has been merged into the auto branch abb54bdf672e583fc40334631f8a6ed39479ab76

**Comment by KoujiroFrau** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [Your tests passed on CircleCI!](https://circleci.com/gh/student-kyushu/frau/46?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

**Pull request merged**
