### PR TITLE
feat: Assign a reviewer randomly

### LINKED ISSUE #33: Assign a reviewer automatically or leave a message
PRs are welcome, but we're human, sometimes don't notice those.
It's user-friendly for frau to assign a reviewer automatically or leave message to ask PR author to assign someone as reviewer if he doesn't assign one in description.
(I guess it's better to assign a reviewer.)

### PR DESCRIPTION
**Pull request by JohnTitor**
Closes #33.

I implemented as follows:

* Assigns a reviewer randomly when author doesn't use `r?` command in description
* Leaves a comment

r? @JohnTitor

### CODE REVIEW

**Comment by JohnTitor** [comment]
I need this patch for fixing bug, so I'll approve myself.

@KoujiroFrau r+

**Comment by KoujiroFrau** [comment]
:pushpin: Commit 2c99e0a70be6725fc1ad48c537bed1d6538603aa has been approved by `JohnTitor`

**Comment by KoujiroFrau** [comment]
:hourglass: 2c99e0a70be6725fc1ad48c537bed1d6538603aa has been merged into the auto branch 6c56f7cbc4dd4044670791fca780f1ff85d50ca2

**Comment by KoujiroFrau** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [Your tests passed on CircleCI!](https://circleci.com/gh/student-kyushu/frau/38?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

**Pull request merged**
