### PR TITLE
Add CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by JohnTitor**
I copied from hibana.

### CODE REVIEW

**Comment by JohnTitor** [comment]
@KoujiroFrau r+

**Comment by KoujiroFrau** [comment]
:pushpin: Commit 831e58c98f940843c9ba858ee5fc19f55e7d916c has been approved by `JohnTitor`

**Comment by KoujiroFrau** [comment]
:hourglass: 831e58c98f940843c9ba858ee5fc19f55e7d916c has been merged into the auto branch 83c6da54f8a60314317ecacfae665b28ba81c4d7

**Comment by JohnTitor** [comment]
@KoujiroFrau r-

**Comment by KoujiroFrau** [comment]
:outbox_tray: This has been cancelled from the approved queue by `JohnTitor`

**Pull request merged**
