### PR TITLE
Enable go modules

### PR DESCRIPTION
**Pull request by JohnTitor**
I forgot enabling go modules in deploy process...

### CODE REVIEW

**Comment by JohnTitor** [comment]
@KoujiroFrau r+

**Comment by KoujiroFrau** [comment]
:pushpin: Commit ae5eda0411bc65a106813c0772ad7a5ae1c0acd2 has been approved by `JohnTitor`

**Comment by KoujiroFrau** [comment]
:postbox: This pull request is queued. Please await the time.

**Comment by KoujiroFrau** [comment]
:hourglass: ae5eda0411bc65a106813c0772ad7a5ae1c0acd2 has been merged into the auto branch 93aa8a82d216637b8c04f0ff1ed711f8d9c59173

**Comment by KoujiroFrau** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [Your tests failed on CircleCI](https://circleci.com/gh/student-kyushu/frau/24?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)
* [The Travis CI build passed](https://travis-ci.org/student-kyushu/frau/builds/496520365?utm_source=github_status&utm_medium=notification)

**Pull request merged**
