### PR TITLE
Request review

### LINKED ISSUE #24: Request review instead of assigning

### PR DESCRIPTION
**Pull request by JohnTitor**
Fixes #24

r? @KoujiroFrau @AjimuNajimi

### CODE REVIEW

**Comment by AjimuNajimi** [comment]
lgtm,

@KoujiroFrau r+

**Comment by AjimuNajimi** [comment]
lgtm,

@KoujiroFrau r+

**Comment by AjimuNajimi** [comment]
lgtm,

@KoujiroFrau r+

**Comment by AjimuNajimi** [comment]
lgtm,

@KoujiroFrau r+

**Comment by KoujiroFrau** [comment]
:pushpin: Commit dd69bb59aaad673a1672dab06c07e1baec73a305 has been approved by `AjimuNajimi`

**Comment by KoujiroFrau** [comment]
:hourglass: dd69bb59aaad673a1672dab06c07e1baec73a305 has been merged into the auto branch f3934bcb001a540737363db3e35e6b707586cbe8

**Comment by JohnTitor** [comment]
@KoujiroFrau r-

**Comment by KoujiroFrau** [comment]
:outbox_tray: This has been cancelled from the approved queue by `JohnTitor`

**Comment by AjimuNajimi** [comment]
lgtm,

@KoujiroFrau r+

**Comment by KoujiroFrau** [comment]
:pushpin: Commit dd69bb59aaad673a1672dab06c07e1baec73a305 has been approved by `AjimuNajimi`

**Comment by KoujiroFrau** [comment]
:hourglass: dd69bb59aaad673a1672dab06c07e1baec73a305 has been merged into the auto branch f3934bcb001a540737363db3e35e6b707586cbe8

**Comment by JohnTitor** [comment]
@KoujiroFrau r-

**Comment by KoujiroFrau** [comment]
:outbox_tray: This has been cancelled from the approved queue by `JohnTitor`

**Comment by KoujiroFrau** [comment]
:pushpin: Commit dd69bb59aaad673a1672dab06c07e1baec73a305 has been approved by `AjimuNajimi`

**Comment by KoujiroFrau** [comment]
:hourglass: dd69bb59aaad673a1672dab06c07e1baec73a305 has been merged into the auto branch f3934bcb001a540737363db3e35e6b707586cbe8

**Comment by KoujiroFrau** [comment]
:outbox_tray: This has been cancelled from the approved queue by `AjimuNajimi`

**Comment by AjimuNajimi** [comment]
@KoujiroFrau r+

**Comment by KoujiroFrau** [comment]
:pushpin: Commit dd69bb59aaad673a1672dab06c07e1baec73a305 has been approved by `AjimuNajimi`

**Comment by KoujiroFrau** [comment]
:hourglass: dd69bb59aaad673a1672dab06c07e1baec73a305 has been merged into the auto branch f3934bcb001a540737363db3e35e6b707586cbe8

**Comment by AjimuNajimi** [comment]
@KoujiroFrau r-

**Comment by KoujiroFrau** [comment]
:outbox_tray: This has been cancelled from the approved queue by `AjimuNajimi`

**Comment by AjimuNajimi** [comment]
@KoujiroFrau r+

**Comment by KoujiroFrau** [comment]
:pushpin: Commit dd69bb59aaad673a1672dab06c07e1baec73a305 has been approved by `AjimuNajimi`

**Comment by KoujiroFrau** [comment]
:hourglass: dd69bb59aaad673a1672dab06c07e1baec73a305 has been merged into the auto branch f3934bcb001a540737363db3e35e6b707586cbe8

**Comment by AjimuNajimi** [comment]
@KoujiroFrau r-

**Comment by KoujiroFrau** [comment]
:outbox_tray: This has been cancelled from the approved queue by `AjimuNajimi`

**Comment by AjimuNajimi** [comment]
@KoujiroFrau r+

**Comment by KoujiroFrau** [comment]
:pushpin: Commit dd69bb59aaad673a1672dab06c07e1baec73a305 has been approved by `AjimuNajimi`

**Comment by KoujiroFrau** [comment]
:hourglass: dd69bb59aaad673a1672dab06c07e1baec73a305 has been merged into the auto branch f3934bcb001a540737363db3e35e6b707586cbe8

**Comment by AjimuNajimi** [comment]
@KoujiroFrau r-

**Comment by KoujiroFrau** [comment]
:outbox_tray: This has been cancelled from the approved queue by `AjimuNajimi`

**Comment by AjimuNajimi** [comment]
@KoujiroFrau r+

**Comment by KoujiroFrau** [comment]
:pushpin: Commit dd69bb59aaad673a1672dab06c07e1baec73a305 has been approved by `AjimuNajimi`

**Comment by KoujiroFrau** [comment]
:hourglass: dd69bb59aaad673a1672dab06c07e1baec73a305 has been merged into the auto branch f3934bcb001a540737363db3e35e6b707586cbe8

**Comment by AjimuNajimi** [comment]
@KoujiroFrau r-

**Comment by KoujiroFrau** [comment]
:outbox_tray: This has been cancelled from the approved queue by `AjimuNajimi`

**Comment by AjimuNajimi** [comment]
@KoujiroFrau r+

**Comment by KoujiroFrau** [comment]
:pushpin: Commit dd69bb59aaad673a1672dab06c07e1baec73a305 has been approved by `AjimuNajimi`

**Comment by KoujiroFrau** [comment]
:hourglass: dd69bb59aaad673a1672dab06c07e1baec73a305 has been merged into the auto branch f3934bcb001a540737363db3e35e6b707586cbe8

**Comment by AjimuNajimi** [comment]
@KoujiroFrau r-

**Comment by KoujiroFrau** [comment]
:outbox_tray: This has been cancelled from the approved queue by `AjimuNajimi`

**Comment by AjimuNajimi** [comment]
@KoujiroFrau r+

**Comment by KoujiroFrau** [comment]
:pushpin: Commit dd69bb59aaad673a1672dab06c07e1baec73a305 has been approved by `AjimuNajimi`

**Comment by KoujiroFrau** [comment]
:hourglass: dd69bb59aaad673a1672dab06c07e1baec73a305 has been merged into the auto branch f3934bcb001a540737363db3e35e6b707586cbe8

**Comment by AjimuNajimi** [comment]
@KoujiroFrau r-

**Comment by KoujiroFrau** [comment]
:outbox_tray: This has been cancelled from the approved queue by `AjimuNajimi`

**Comment by JohnTitor** [comment]
We should think over review process, I want to start over this.

**Pull request closed without merging**
