### PR TITLE
Update webhook events on README

### PR DESCRIPTION
**Pull request by JohnTitor**
update and sort the list of webhook events on README

r? @ghost

### CODE REVIEW

**Comment by JohnTitor** [comment]
@frautaso r+

**Comment by frautaso** [comment]
:pushpin: Commit f899764288ce0de1b5f0d063005e63667fe69cbe has been approved by `JohnTitor`

**Comment by frautaso** [comment]
:hourglass: f899764288ce0de1b5f0d063005e63667fe69cbe has been merged into the auto branch 80400724712a129564691dc49541998e746a0db7

**Comment by frautaso** [comment]
:tada: The result of what tried to merge this pull request is `success`.

**Pull request merged**
