### PR TITLE
test: Replace ON with on

### PR DESCRIPTION
**Pull request by JohnTitor**
Only god knows...

### CODE REVIEW

**Comment by JohnTitor** [comment]
@KoujiroFrau r=me

**Comment by KoujiroFrau** [comment]
:pushpin: Commit 7e3e10a7467da7672c707da95e0c4c9553fbf19c has been approved by JohnTitor

**Comment by KoujiroFrau** [comment]
:hourglass: 7e3e10a7467da7672c707da95e0c4c9553fbf19c has been merged into the auto branch 9ec05b978566748e12cf42c2f0e25280aaea170d

**Comment by KoujiroFrau** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build is in progress](https://travis-ci.org/student-kyushu/frau/builds/496526361?utm_source=github_status&utm_medium=notification)
* [Your tests passed on CircleCI!](https://circleci.com/gh/student-kyushu/frau/26?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

**Pull request merged**
