### PR TITLE
docs: Improve README

### PR DESCRIPTION
**Pull request by JohnTitor**
I updated as follows:

* Changes title
* Removes Travis CI badge(see #55)
* Improves and adds features' description
* Removes unnecessary links

### CODE REVIEW

**Comment by JohnTitor** [comment]
@KoujiroFrau r=me

**Comment by KoujiroFrau** [comment]
:pushpin: Commit a3ba2c7dcecf730f3d2b25c248c87d07fea9f64a has been approved by JohnTitor

**Comment by KoujiroFrau** [comment]
:hourglass: a3ba2c7dcecf730f3d2b25c248c87d07fea9f64a has been merged into the auto branch 05e08e9350b689849fff3e6dc7acc12ffc713add

**Comment by KoujiroFrau** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [Your tests passed on CircleCI!](https://circleci.com/gh/student-kyushu/frau/34?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

**Pull request merged**
