### PR TITLE
Forbid to merge if there is label `S-do-not-merge`

### LINKED ISSUE #15: Support label `Do-not-merge`
Sometimes we don't want to merge a PR yet, so the label `Do-not-merge` is useful.

### PR DESCRIPTION
**Pull request by JohnTitor**
resolve #15 

r? @JohnTitor

### CODE REVIEW

**Comment by JohnTitor** [comment]
@KoujiroFrau r+

**Comment by KoujiroFrau** [comment]
:pushpin: Commit edfc1603520c21f2937be83ca86685393fb2789e has been approved by `JohnTitor`

**Comment by KoujiroFrau** [comment]
:hourglass: edfc1603520c21f2937be83ca86685393fb2789e has been merged into the auto branch 77388dfe73e1372e5013e940f13fb15d98f77ce3

**Comment by JohnTitor** [comment]
@KoujiroFrau  r-

**Comment by KoujiroFrau** [comment]
:outbox_tray: This has been cancelled from the approved queue by `JohnTitor`

**Comment by JohnTitor** [comment]
@KoujiroFrau r+

**Comment by KoujiroFrau** [comment]
:warning: Forbid to merge by label `S-do-not-merge`

**Comment by JohnTitor** [comment]
@KoujiroFrau r+

**Comment by KoujiroFrau** [comment]
:pushpin: Commit 7a56a71dd0f9bcbe6abe28870de01b7035cda7f5 has been approved by `JohnTitor`

**Comment by KoujiroFrau** [comment]
:hourglass: 7a56a71dd0f9bcbe6abe28870de01b7035cda7f5 has been merged into the auto branch b3662230993f29d9c9099d8896246f9143a8d9e5

**Comment by KoujiroFrau** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/student-kyushu/frau/builds/487968076?utm_source=github_status&utm_medium=notification)

**Pull request merged**
